name: velib_project
version: 1.0.0
config-version: 2

profile: velib_project_profile  # correspond à ton profile dans profiles.yml

# Répertoire des modèles DBT
model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"        # fichiers compilés
clean-targets: ["target", "dbt_modules"]

models:
  velib_project:
    raw:
      +schema: raw         
      +materialized: table
    staging:
      +schema: staging
      +materialized: table
    intermediate:
      +schema: intermediate
      +materialized: view   
    marts:
      core:
        +materialized: table
        +schema: marts
      analytics:
        +materialized: table
        +schema: marts
      reporting:
        +materialized: view
        +schema: marts